name: Build Windows EXE

on:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed csv_dedup_gui.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: dedup_tool_windows_exe
          path: dist/csv_dedup_gui.exe

